// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cusum
NumericVector cusum(NumericVector x);
RcppExport SEXP _eNchange_cusum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum(x));
    return rcpp_result_gen;
END_RCPP
}
// finner_prod_maxp
List finner_prod_maxp(NumericVector out, double p);
RcppExport SEXP _eNchange_finner_prod_maxp(SEXP outSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type out(outSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(finner_prod_maxp(out, p));
    return rcpp_result_gen;
END_RCPP
}
// timeChangeTrans
NumericVector timeChangeTrans(NumericVector t_i, NumericVector par);
RcppExport SEXP _eNchange_timeChangeTrans(SEXP t_iSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t_i(t_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(timeChangeTrans(t_i, par));
    return rcpp_result_gen;
END_RCPP
}
// hawkesLike
double hawkesLike(NumericVector t_i, NumericVector par);
RcppExport SEXP _eNchange_hawkesLike(SEXP t_iSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t_i(t_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(hawkesLike(t_i, par));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eNchange_cusum", (DL_FUNC) &_eNchange_cusum, 1},
    {"_eNchange_finner_prod_maxp", (DL_FUNC) &_eNchange_finner_prod_maxp, 2},
    {"_eNchange_timeChangeTrans", (DL_FUNC) &_eNchange_timeChangeTrans, 2},
    {"_eNchange_hawkesLike", (DL_FUNC) &_eNchange_hawkesLike, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_eNchange(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
