# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cusum <- function(x) {
    .Call(`_eNchange_cusum`, x)
}

finner_prod_maxp <- function(out, p) {
    .Call(`_eNchange_finner_prod_maxp`, out, p)
}

timeChangeTrans <- function(t_i, par) {
    .Call(`_eNchange_timeChangeTrans`, t_i, par)
}

hawkesLike <- function(t_i, par) {
    .Call(`_eNchange_hawkesLike`, t_i, par)
}

